org: niccdev
console: false
service: form-notification
useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-1
  memorySize: 512
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
plugins:
  - serverless-offline
  - serverless-dotenv-plugin